project:
  type: website

website:
  title: "Juan Pablo C. H."
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Blog archive"
        file: posts.qmd 
    right:
      - about.qmd
      - icon: github
        href: https://github.com/juanpa-biotech
  google-analytics: ""
  site-url: https://juanpacarreon.com/

format:
  html:
    theme: simplex
    linkcolor: "#6633c4"
    code-copy: true
    footnotes-hover: true
    css: styles.css