project:
  type: website

website:
  title: "Juan Pablo Carreón Hidalgo"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/juanpa-biotech
      - icon: twitter
        href: https://twitter.com/juanpa_biotech
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

googleAnalytics: 